apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
  - image: diskover
    context: .
    docker:
      network: host
      dockerfile: Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/diskover:{{.VERSION}}'
